FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o faturamento-service

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/faturamento-service /faturamento-service
EXPOSE 8082
ENTRYPOINT ["/faturamento-service"]